"""Add outfits, item_images, outfit_items tables

Revision ID: 280b030e7d45
Revises: 87209fa21599
Create Date: 2025-12-06 17:27:10.895693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280b030e7d45'
down_revision: Union[str, None] = '87209fa21599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create new tables
    op.create_table(
        'outfits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('occasion', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),  # don't set server_default here for SQLite
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfits_id'), 'outfits', ['id'], unique=False)

    op.create_table(
        'item_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_id'), 'item_images', ['id'], unique=False)

    op.create_table(
        'outfit_items',
        sa.Column('outfit_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id']),
        sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id']),
        sa.PrimaryKeyConstraint('outfit_id', 'item_id')
    )

    # Add created_at to existing 'items' table
    op.add_column(
        'items',
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True)
    )

    # Fill existing rows with current timestamp (run after column is added)
    op.execute("UPDATE items SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'created_at')
    op.drop_table('outfit_items')
    op.drop_index(op.f('ix_item_images_id'), table_name='item_images')
    op.drop_table('item_images')
    op.drop_index(op.f('ix_outfits_id'), table_name='outfits')
    op.drop_table('outfits')
    # ### end Alembic commands ###
